on:
  workflow_dispatch:
    inputs:
      link:
        description: "Captcha Link"
        required: true
        default: "https://app.blasteronline.com/assets/captcha/1652640112.293.jpg"
name: Get Captcha
jobs:
  get:
    name: Get Captcha
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v2
      - run: sudo apt update
      - run: echo $link;
        env:
          link: ${{ github.event.inputs.link }}
      - run: sudo apt install tesseract-ocr -y
      - run: pip install requests pytesseract opencv-python
      - run: python main.py $link > captcha.txt
        env:
          link: ${{ github.event.inputs.link }}
      - uses: actions/upload-artifact@v2
        with:
          name: captcha.txt
          path: captcha.txt
          
